/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseLabz REST API
 * Contract-first OpenAPI spec for the WiseLabz frontend. This is the source of truth the frontend generates against (orval) and mocks against (MSW) BEFORE the Go backend exists. The backend implements *to* this spec. Keep this file and docs/WS_CONTRACT.md in sync with docs/FRONTEND_PLAN.md (§1 endpoints, §4 WS).
 *
 * OpenAPI spec version: 0.1.0
 */

export type PostConnectorsConnectorIdRestartBody = {
  /** Target entity's SnapshotEntity.externalId (e.g. a VM ID, container ID, or service name), or omitted for connectors that manage a single implicit service. Ignored for dry-run previews. */
  entityRef?: string;
};
